"use client";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { useState } from "react";
import { type Message, continueConversationTest } from "@/lib/ai/actions";
import { buttonVariants } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import { Loader2Icon } from "lucide-react";

export function AddQuizDialog({ lessonId }: { lessonId: string }) {
  const [conversation, setConversation] = useState<Message>();
  const [input, setInput] = useState<string>("");
  const [isopen, setIsOpen] = useState<boolean>(false);
  const [isGenerating, setIsGenerating] = useState<boolean>(true);

  return (
    <Dialog
      open={isopen}
      onOpenChange={(v) => {
        if (!v) setIsOpen(v);
      }}
    >
      <DialogTrigger
        className={`${buttonVariants({ variant: "outline" })} cursor-pointer rounded-md`}
        asChild
        onClick={() => setIsOpen(true)}
      >
        <p>Add quiz </p>
      </DialogTrigger>
      <DialogContent className={`w-fit sm:max-w-[780px]`}>
        <DialogHeader>
          <DialogTitle>Create a New Quiz</DialogTitle>
          <DialogDescription>
            Provide a subject for the quiz and it will get generated by AI
          </DialogDescription>
        </DialogHeader>
        <div>
          {!isGenerating ? (
            <div>{conversation && <div>{conversation.display}</div>}</div>
          ) : (
            <div className="flex items-center justify-center p-5">
              <Loader2Icon className="animate-spin text-mainblue" />
            </div>
          )}
          <form
            className={cn(
              "flex justify-between gap-2 ",
              conversation ? "pt-4" : "pt-0",
            )}
            onSubmit={async (e) => {
              e.preventDefault();
              setIsGenerating(true);
              const message = await continueConversationTest(input, lessonId);
              setIsGenerating(false);
              setConversation(message);
            }}
          >
            <Input
              type="text"
              value={input}
              onChange={(event) => {
                setInput(event.target.value);
              }}
            />
          </form>
        </div>
      </DialogContent>
    </Dialog>
  );
}
