"use client";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
// import { PlusIcon } from "@heroicons/react/24/outline";

import { useFormState } from "react-dom";
import { addCourse } from "@/actions/helpers/courseHelpers";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { type Message, continueConversationTest } from "@/lib/ai/actions";
import { Button, buttonVariants } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { cn } from "@/lib/utils";

export function AddQuizDialog() {
  const router = useRouter();
  const [state, formAction] = useFormState(addCourse, {
    error: null,
    type: null,
  });
  const [conversation, setConversation] = useState<Message>();
  const [input, setInput] = useState<string>("");

  const [isopen, setIsOpen] = useState<boolean>(false);
  useEffect(() => {
    if (state.type?.success) {
      setIsOpen(false);
      router.push(`/dashboard/mycourses/${state.error?.success}/edit`);
    } else console.log("not working ", state.error);
  }, [state, router]);
  return (
    <Dialog
      open={isopen}
      onOpenChange={(v) => {
        if (!v) setIsOpen(v);
      }}
    >
      <DialogTrigger
        className={`${buttonVariants({ variant: "outline" })} rounded-md`}
        asChild
        onClick={() => setIsOpen(true)}
      >
        <p>Add quiz </p>
      </DialogTrigger>
      <DialogContent className={`w-fit sm:max-w-[780px]`}>
        <DialogHeader>
          <DialogTitle>Create a New Quiz</DialogTitle>
          <DialogDescription>
            Provide a subject for the quiz and it will get generated by AI
          </DialogDescription>
        </DialogHeader>
        <div>
          <div>{conversation && <div>{conversation.display}</div>}</div>
          <form
            className={cn(
              "flex justify-between gap-2 ",
              conversation ? "pt-4" : "pt-0",
            )}
            onSubmit={async (e) => {
              e.preventDefault();
              const message = await continueConversationTest(input);

              setConversation(message);
            }}
          >
            <Input
              type="text"
              value={input}
              onChange={(event) => {
                setInput(event.target.value);
              }}
            />
          </form>
        </div>
      </DialogContent>
    </Dialog>
  );
}
