import NavBar from "@/components/navbar";
import "@/styles/globals.css";

import { Jost } from "next/font/google";

const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`pt-10 font-sans ${jost.className}`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
